[release]
address = "127.0.0.1"
port = 8080
workers = 8
keep_alive = 5
ident = "Rocket"
ip_header = "X-Real-IP" # set to `false` to disable
log_level = "normal"
temp_dir = "/tmp"
cli_colors = true
ctrlc = false
